[package]
name = "common"
edition.workspace = true
version.workspace = true
author.workspace = true
description.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
